language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python -m unittest discover
  - coverage run tests.py
after_success:
  - codecov