language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python -m unittest discover
  - coverage run test_charts.py
after_success:
  - codecov